services:
  app:
    build: .

    ports: 
      - "8000:8000"

    env_file:
      - .env

    environment:
      DB_HOST: postgres
      ELASTIC_HOST: elasticsearch

    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
 

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - search_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:9.4.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  ui:
    build: .
    command: streamlit run ui.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      API_URL: http://app:8000
    depends_on:
      - app
    

volumes:
  search_pgdata:
